### ISSUE TITLE
request: Spotify lyrics

### ISSUE THREAD

**Issue by crashigerlp** [rxri/spicetify-extensions#4] opened 2024-05-20 19:04 UTC
### 📦 Extension name

adblockify

### 📝 Provide a description of the new feature

Is there any chance, that you could unlock the lyrics for spotify? I know that lyrixed exists, but it only has lyrics for a few songs.

**Comment by rxri** [comment] 2024-05-20 19:44
Duplicate of #1

**Closed by rxri** 2024-05-20 19:45 UTC
Labels: request
