### ISSUE TITLE
bug: adblockify: Failed inside

### ISSUE THREAD

**Issue by pO0P3R125** [rxri/spicetify-extensions#7] opened 2024-05-28 04:25 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Most up-to-date (1.2.38.720)
- Spicetify version: Most up-to-date(1.2.38.720.ga4a700e)
Windows 10
```

### 📦 Extension name

adblockify

### 📝 Description

It's a message getting spam about adblockify throwing an exception, adblockify works fine but I would like to optimize my spicetify experience
```
adblockify: Failed inside `configureAdManagers` function
 TypeError: Cannot read properties of undefined (reading 'increaseStreamTime')
    at configureAdManagers (adblock.js?time=1716869560299:90:52)
    at handleAdSlot (adblock.js?time=1716869560299:135:9)
    at xpui.js:1:1786557
    at vendor~xpui.js:1:5966318
    at onSuccess (xpui.js:1:3118922)
```

### 📸 Screenshots

![Spotify_RzmSgyBQc5](https://github.com/rxri/spicetify-extensions/assets/43865463/52c0cf30-72ad-4bcb-8e41-4df750cf1cc6)

**Comment by rxri** [comment] 2024-05-28 12:09
Not a fault of the extension. The issue is on your end, but I will use different way to set it anyway. fixed by https://github.com/rxri/spicetify-extensions/commit/96c03d40518f6527db9b4122cb628d88f36f47d0

**Closed by rxri** 2024-05-28 12:09 UTC
Labels: bug
