### ISSUE TITLE
Free lyrics

### ISSUE THREAD

**Issue by TrustJump** [rxri/spicetify-extensions#2] opened 2024-05-14 17:04 UTC
### 📝 Provide a description of the new feature

So spotify started making so only premium users could use lyrics. 
I hate that they did this. may u add lyrics to it please?

**Comment by rxri** [comment] 2024-05-14 17:08
duplicate of https://github.com/rxri/spicetify-extensions/issues/1

**Closed by rxri** 2024-05-14 17:08 UTC
Labels: request
